//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NettlyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingList
    {
        public int WaitingListID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DesiredDate { get; set; }
        public Nullable<System.TimeSpan> DesiredSlot { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
